---
# tasks file for lynis
- name: Install deps
  yum:
    name:
      - ca-certificates
      - curl
      - nss
      - openssl
    state: latest

- name: Add multiple repositories into the same file (1/2)
  yum_repository:
    name: lynis
    description: CISOfy Software - Lynis package
    baseurl: https://packages.cisofy.com/community/lynis/rpm/
    enabled: yes
    gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    gpgcheck: yes
    priority: 2

- name: Install Lynis
  yum:
    name: lynis
    state: latest
    update_cache: yes
